# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Player(object):
    
    _NATIONALITIES = {1:"AFGHANISTAN", 191:"ALBANIA", 44:"ALGERIA", 161:"AMERICAN SAMOA", 192:"ANDORRA", 45:"ANGOLA", 103:"ANGUILLA", 104:"ANTIGUA AND BARBUDA", 144:"ARGENTINA", 193:"ARMENIA", 105:"ARUBA", 162:"AUSTRALIA", 194:"AUSTRIA", 195:"AZERBAIJAN", 2:"BAHRAIN", 3:"BANGLADESH", 107:"BARBADOS", 196:"BELARUS", 197:"BELGIUM", 108:"BELIZE", 46:"BENIN", 109:"BERMUDA", 4:"BHUTAN", 145:"BOLIVIA", 198:"BOSNIA AND HERZEGOVINA", 47:"BOTSWANA", 146:"BRAZIL", 136:"BRITISH VIRGIN ISLANDS", 5:"BRUNEI", 199:"BULGARIA", 48:"BURKINA FASO", 49:"BURUNDI", 6:"CAMBODIA", 50:"CAMEROON", 110:"CANADA", 51:"CAPE VERDE", 111:"CAYMAN ISLANDS", 52:"CENTRAL AFRICAN REP.", 53:"CHAD", 147:"CHILE", 7:"CHINA", 148:"COLOMBIA", 98:"CONGO", 55:"CONGO DR", 163:"COOK ISLANDS", 112:"COSTA RICA", 56:"CÔTE D'IVOIRE", 200:"CROATIA", 113:"CUBA", 140:"CURAÇAO", 201:"CYPRUS", 202:"CZECH REPUBLIC", 203:"DENMARK", 57:"DJIBOUTI", 114:"DOMINICA", 115:"DOMINICAN REPUBLIC", 43:"EAST TIMOR", 149:"ECUADOR", 58:"EGYPT", 116:"EL SALVADOR", 204:"ENGLAND", 59:"EQUATORIAL GUINEA", 60:"ERITREA", 205:"ESTONIA", 61:"ETHIOPIA", 206:"FAROE ISLANDS", 164:"FIJI", 207:"FINLAND", 208:"FRANCE", 138:"FRENCH GUIANA", 62:"GABON", 209:"GEORGIA", 210:"GERMANY", 64:"GHANA", 245:"GIBRALTAR", 211:"GREECE", 117:"GRENADA", 118:"GUADELOUPE", 176:"GUAM", 119:"GUATEMALA", 65:"GUINEA", 66:"GUINEA-BISSAU", 159:"GUYANA", 120:"HAITI", 121:"HONDURAS", 8:"HONG KONG", 212:"HUNGARY", 213:"ICELAND", 9:"INDIA", 10:"INDONESIA", 11:"IRAN", 12:"IRAQ", 214:"IRELAND", 189:"ISRAEL", 215:"ITALY", 122:"JAMAICA", 13:"JAPAN", 14:"JORDAN", 216:"KAZAKHSTAN", 67:"KENYA", 311:"KOSOVO", 17:"KUWAIT", 40:"KYRGYZ REPUBLIC", 18:"LAOS", 217:"LATVIA", 19:"LEBANON", 68:"LESOTHO", 69:"LIBERIA", 70:"LIBYA", 218:"LIECHTENSTEIN", 219:"LITHUANIA", 220:"LUXEMBOURG", 20:"MACAO", 221:"MACEDONIA", 71:"MADAGASCAR", 72:"MALAWI", 21:"MALAYSIA", 22:"MALDIVES", 73:"MALI", 222:"MALTA", 123:"MARTINIQUE", 74:"MAURITANIA", 75:"MAURITIUS", 124:"MEXICO", 223:"MOLDOVA", 250:"MONACO", 23:"MONGOLIA", 304:"MONTENEGRO", 125:"MONTSERRAT", 76:"MOROCCO", 77:"MOZAMBIQUE", 24:"MYANMAR", 78:"NAMIBIA", 25:"NEPAL", 224:"NETHERLANDS", 126:"NETHERLANDS ANTILLES", 165:"NEW CALEDONIA", 166:"NEW ZEALAND", 127:"NICARAGUA", 79:"NIGER", 80:"NIGERIA", 15:"NORTH KOREA", 225:"NORTHERN IRELAND", 226:"NORWAY", 26:"OMAN", 260:"Others", 27:"PAKISTAN", 184:"PALAU", 28:"PALESTINE", 128:"PANAMA", 167:"PAPUA NEW GUINEA", 150:"PARAGUAY", 151:"PERU", 29:"PHILIPPINES", 227:"POLAND", 228:"PORTUGAL", 129:"PUERTO RICO", 30:"QATAR", 63:"REPUBLIC OF THE GAMBIA", 100:"RÉUNION", 229:"ROMANIA", 230:"RUSSIA", 81:"RWANDA", 130:"SAINT KITTS AND NEVIS", 131:"SAINT LUCIA", 168:"SAMOA", 231:"SAN MARINO", 82:"SÃO TOMÉ AND PRÍNCIPE", 31:"SAUDI ARABIA", 232:"SCOTLAND", 83:"SENEGAL", 303:"SERBIA", 84:"SEYCHELLES", 85:"SIERRA LEONE", 32:"SINGAPORE", 310:"SINT MAARTEN", 234:"SLOVAKIA", 235:"SLOVENIA", 169:"SOLOMON ISLANDS", 86:"SOMALIA", 87:"SOUTH AFRICA", 16:"SOUTH KOREA", 312:"SOUTH SUDAN", 236:"SPAIN", 33:"SRI LANKA", 132:"ST VINCENT & GRENADINES", 88:"SUDAN", 139:"SURINAME", 89:"SWAZILAND", 237:"SWEDEN", 238:"SWITZERLAND", 34:"SYRIA", 170:"TAHITI", 298:"TAIWAN", 41:"TAJIKISTAN", 90:"TANZANIA", 36:"THAILAND", 106:"THE BAHAMAS", 54:"THE COMOROS", 91:"TOGO", 171:"TONGA", 133:"TRINIDAD AND TOBAGO", 92:"TUNISIA", 190:"TURKEY", 42:"TURKMENISTAN", 134:"TURKS AND CAICOS IS.", 137:"U.S. VIRGIN ISLANDS", 37:"UAE", 93:"UGANDA", 239:"UKRAINE", 135:"UNITED STATES", 152:"URUGUAY", 240:"UZBEKISTAN", 172:"VANUATU", 153:"VENEZUELA", 38:"VIETNAM", 241:"WALES", 39:"YEMEN", 94:"ZAMBIA", 95:"ZIMBABWE"}
    
    _NATINDEX = {}
    
    _PLAYSTYLES = {0:"None", 1:"Goal Poacher", 2:"Dummy Runner", 3:"Fox in the Box", 4:"Prolific Winger", 5:"Classic No. 10", 6:"Hole Player", 7:"Box to Box", 8:"Anchor Man", 9:"The Destroyer", 10:"Extra Frontman", 11:"Offensive Fullback", 12:"Defensive Fullback", 13:"Target Man", 14:"Creative Playmaker", 15:"Build Up", 16:"Offensive Goalkeeper", 17:"Defensive Goalkeeper"}
    
    _POSITIONS = {0:"Goalkeeper", 1:"Centre Back", 2:"Left Back", 3:"Right Back", 4:"Defensive Midfielder", 5:"Centre Midfielder", 6:"Left Midfielder", 7:"Right Midfielder", 8:"Attacking Midfielder", 9:"Left Wing Forward", 10:"Right Wing Forward", 11:"Second Striker", 12:"Centre Forward"}
    
    _SKINCOLOURS = {1:"Light", 2:"Fair", 3:"Medium", 4:"Olive", 5:"Brown", 6:"Black", 7:"Transparent", 0:"Normal"}
    
    _PLAYABLES = {}
    _STATS = []
    _SKILLS = []
    _COMSTYLES = []
    valid = QtGui.QIntValidator(0, 99)

    def setupUi(self, Player):
        self._PLAYABLES.clear()
        del self._STATS [:]
        del self._SKILLS [:]
        del self._COMSTYLES [:]
        Player.setObjectName("Player")
        Player.resize(1110, 870)
        Player.setMinimumSize(QtCore.QSize(1110, 870))
        Player.setMaximumSize(QtCore.QSize(1110, 870))
        self.centralwidget = QtWidgets.QWidget(Player)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1090, 855))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 461))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 0, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pid = QtWidgets.QLineEdit(self.groupBox)
        self.pid.setGeometry(QtCore.QRect(120, 40, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pid.setFont(font)
        self.pid.setObjectName("pid")
        self.pid.setValidator(QtGui.QIntValidator(0, 999999999))
        self.pid.setReadOnly(1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pname = QtWidgets.QLineEdit(self.groupBox)
        self.pname.setGeometry(QtCore.QRect(120, 70, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pname.setFont(font)
        self.pname.setObjectName("pname")
        self.pname.setMaxLength(45)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pshirtname = QtWidgets.QLineEdit(self.groupBox)
        self.pshirtname.setGeometry(QtCore.QRect(120, 100, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pshirtname.setFont(font)
        self.pshirtname.setObjectName("pshirtname")
        self.pshirtname.setMaxLength(17)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pcommid = QtWidgets.QLineEdit(self.groupBox)
        self.pcommid.setGeometry(QtCore.QRect(120, 130, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pcommid.setFont(font)
        self.pcommid.setObjectName("pcommid")
        self.pcommid.setValidator(QtGui.QIntValidator(0, 4294967295))
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pnationality = QtWidgets.QComboBox(self.groupBox)
        self.pnationality.setGeometry(QtCore.QRect(120, 160, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pnationality.setFont(font)
        self.pnationality.setObjectName("pnationality")
        self.pnationality.setMaxVisibleItems(20)
        
        i = 0
        for id, nat in self._NATIONALITIES.items():
            self.pnationality.addItem(nat, id)
            self._NATINDEX[id] = i
            i = i + 1
        
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pplayingstyle = QtWidgets.QComboBox(self.groupBox)
        self.pplayingstyle.setGeometry(QtCore.QRect(120, 190, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pplayingstyle.setFont(font)
        self.pplayingstyle.setObjectName("pplayingstyle")
        self.pplayingstyle.setMaxVisibleItems(20)
        
        for id, style in self._PLAYSTYLES.items():
            self.pplayingstyle.addItem(style, id)
        
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.page = QtWidgets.QLineEdit(self.groupBox)
        self.page.setGeometry(QtCore.QRect(120, 220, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.page.setFont(font)
        self.page.setObjectName("page")
        self.page.setMaxLength(3)
        self.page.setValidator(QtGui.QIntValidator(0, 999))
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pheight = QtWidgets.QLineEdit(self.groupBox)
        self.pheight.setGeometry(QtCore.QRect(120, 250, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pheight.setFont(font)
        self.pheight.setObjectName("pheight")
        self.pheight.setMaxLength(4)
        self.pheight.setValidator(QtGui.QIntValidator(0, 9999))
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 280, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pweight = QtWidgets.QLineEdit(self.groupBox)
        self.pweight.setGeometry(QtCore.QRect(120, 280, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pweight.setFont(font)
        self.pweight.setObjectName("pweight")
        self.pweight.setMaxLength(4)
        self.pweight.setValidator(QtGui.QIntValidator(0, 9999))
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 310, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pform = QtWidgets.QComboBox(self.groupBox)
        self.pform.setGeometry(QtCore.QRect(120, 310, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pform.setFont(font)
        self.pform.setObjectName("pform")
        
        for i in range(8):
            self.pform.addItem(str(i+1), i)
        
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 340, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.pfooting = QtWidgets.QComboBox(self.groupBox)
        self.pfooting.setGeometry(QtCore.QRect(120, 340, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pfooting.setFont(font)
        self.pfooting.setObjectName("pfooting")
        
        self.pfooting.addItem("Right Foot", 0)
        self.pfooting.addItem("Left Foot", 1)
        
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 370, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pwfacc = QtWidgets.QComboBox(self.groupBox)
        self.pwfacc.setGeometry(QtCore.QRect(120, 370, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pwfacc.setFont(font)
        self.pwfacc.setObjectName("pwfacc")
        
        for i in range(4):
            self.pwfacc.addItem(str(i+1), i)
        
        self.pwfusage = QtWidgets.QComboBox(self.groupBox)
        self.pwfusage.setGeometry(QtCore.QRect(230, 370, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pwfusage.setFont(font)
        self.pwfusage.setObjectName("pwfusage")
        
        for i in range(4):
            self.pwfusage.addItem(str(i+1), i)
        
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 400, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pinjuryres = QtWidgets.QComboBox(self.groupBox)
        self.pinjuryres.setGeometry(QtCore.QRect(120, 400, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pinjuryres.setFont(font)
        self.pinjuryres.setObjectName("pinjuryres")
        
        for i in range(3):
            self.pinjuryres.addItem(str(i+1), i)
        
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 480, 351, 341))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.pregpos = QtWidgets.QComboBox(self.groupBox_2)
        self.pregpos.setGeometry(QtCore.QRect(120, 40, 160, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pregpos.setFont(font)
        self.pregpos.setObjectName("pregpos")
        self.pregpos.setMaxVisibleItems(20)
        
        for id, pos in self._POSITIONS.items():
            self.pregpos.addItem(pos, id)
        
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 80, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.posss = QtWidgets.QPushButton(self.groupBox_2)
        self.posss.setGeometry(QtCore.QRect(110, 90, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posss.setFont(font)
        self.posss.setObjectName("posss")
        self._PLAYABLES[1] = self.posss
        self.poscf = QtWidgets.QPushButton(self.groupBox_2)
        self.poscf.setGeometry(QtCore.QRect(170, 90, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.poscf.setFont(font)
        self.poscf.setObjectName("poscf")
        self._PLAYABLES[0] = self.poscf
        self.poslwf = QtWidgets.QPushButton(self.groupBox_2)
        self.poslwf.setGeometry(QtCore.QRect(80, 140, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.poslwf.setFont(font)
        self.poslwf.setObjectName("poslwf")
        self._PLAYABLES[2] = self.poslwf
        self.posamf = QtWidgets.QPushButton(self.groupBox_2)
        self.posamf.setGeometry(QtCore.QRect(140, 140, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posamf.setFont(font)
        self.posamf.setObjectName("posamf")
        self._PLAYABLES[4] = self.posamf
        self.posrwf = QtWidgets.QPushButton(self.groupBox_2)
        self.posrwf.setGeometry(QtCore.QRect(200, 140, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posrwf.setFont(font)
        self.posrwf.setObjectName("posrwf")
        self._PLAYABLES[3] = self.posrwf
        self.poslmf = QtWidgets.QPushButton(self.groupBox_2)
        self.poslmf.setGeometry(QtCore.QRect(50, 190, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.poslmf.setFont(font)
        self.poslmf.setObjectName("poslmf")
        self._PLAYABLES[7] = self.poslmf
        self.posdmf = QtWidgets.QPushButton(self.groupBox_2)
        self.posdmf.setGeometry(QtCore.QRect(110, 190, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posdmf.setFont(font)
        self.posdmf.setObjectName("posdmf")
        self._PLAYABLES[5] = self.posdmf
        self.poscmf = QtWidgets.QPushButton(self.groupBox_2)
        self.poscmf.setGeometry(QtCore.QRect(170, 190, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.poscmf.setFont(font)
        self.poscmf.setObjectName("poscmf")
        self._PLAYABLES[6] = self.poscmf
        self.posrmf = QtWidgets.QPushButton(self.groupBox_2)
        self.posrmf.setGeometry(QtCore.QRect(230, 190, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posrmf.setFont(font)
        self.posrmf.setObjectName("posrmf")
        self._PLAYABLES[8] = self.posrmf
        self.poslb = QtWidgets.QPushButton(self.groupBox_2)
        self.poslb.setGeometry(QtCore.QRect(80, 240, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.poslb.setFont(font)
        self.poslb.setObjectName("poslb")
        self._PLAYABLES[10] = self.poslb
        self.poscb = QtWidgets.QPushButton(self.groupBox_2)
        self.poscb.setGeometry(QtCore.QRect(140, 240, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.poscb.setFont(font)
        self.poscb.setObjectName("poscb")
        self._PLAYABLES[9] = self.poscb
        self.posrb = QtWidgets.QPushButton(self.groupBox_2)
        self.posrb.setGeometry(QtCore.QRect(200, 240, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posrb.setFont(font)
        self.posrb.setObjectName("posrb")
        self._PLAYABLES[11] = self.posrb
        self.posgk = QtWidgets.QPushButton(self.groupBox_2)
        self.posgk.setGeometry(QtCore.QRect(140, 290, 55, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posgk.setFont(font)
        self.posgk.setObjectName("posgk")
        self._PLAYABLES[12] = self.posgk
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 10, 241, 811))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.pattprow = QtWidgets.QLineEdit(self.groupBox_3)
        self.pattprow.setGeometry(QtCore.QRect(10, 40, 60, 25))
        self.pattprow.setObjectName("pattprow")
        self.pattprow.setAlignment(QtCore.Qt.AlignCenter)
        self.pattprow.setMaxLength(2)
        self.pattprow.setValidator(self.valid)
        self._STATS.append(self.pattprow)
        self.pdefprow = QtWidgets.QLineEdit(self.groupBox_3)
        self.pdefprow.setGeometry(QtCore.QRect(10, 70, 60, 25))
        self.pdefprow.setObjectName("pdefprow")
        self.pdefprow.setAlignment(QtCore.Qt.AlignCenter)
        self.pdefprow.setMaxLength(2)
        self.pdefprow.setValidator(self.valid)
        self._STATS.append(self.pdefprow)
        self.pgoalkeeping = QtWidgets.QLineEdit(self.groupBox_3)
        self.pgoalkeeping.setGeometry(QtCore.QRect(10, 100, 60, 25))
        self.pgoalkeeping.setObjectName("pgoalkeeping")
        self.pgoalkeeping.setAlignment(QtCore.Qt.AlignCenter)
        self.pgoalkeeping.setMaxLength(2)
        self.pgoalkeeping.setValidator(self.valid)
        self._STATS.append(self.pgoalkeeping)
        self.pdribbling = QtWidgets.QLineEdit(self.groupBox_3)
        self.pdribbling.setGeometry(QtCore.QRect(10, 130, 60, 25))
        self.pdribbling.setObjectName("pdribbling")
        self.pdribbling.setAlignment(QtCore.Qt.AlignCenter)
        self.pdribbling.setMaxLength(2)
        self.pdribbling.setValidator(self.valid)
        self._STATS.append(self.pdribbling)
        self.pfinishing = QtWidgets.QLineEdit(self.groupBox_3)
        self.pfinishing.setGeometry(QtCore.QRect(10, 160, 60, 25))
        self.pfinishing.setObjectName("pfinishing")
        self.pfinishing.setAlignment(QtCore.Qt.AlignCenter)
        self.pfinishing.setMaxLength(2)
        self.pfinishing.setValidator(self.valid)
        self._STATS.append(self.pfinishing)
        self.plowpass = QtWidgets.QLineEdit(self.groupBox_3)
        self.plowpass.setGeometry(QtCore.QRect(10, 190, 60, 25))
        self.plowpass.setObjectName("plowpass")
        self.plowpass.setAlignment(QtCore.Qt.AlignCenter)
        self.plowpass.setMaxLength(2)
        self.plowpass.setValidator(self.valid)
        self._STATS.append(self.plowpass)
        self.ploftedpass = QtWidgets.QLineEdit(self.groupBox_3)
        self.ploftedpass.setGeometry(QtCore.QRect(10, 220, 60, 25))
        self.ploftedpass.setObjectName("ploftedpass")
        self.ploftedpass.setAlignment(QtCore.Qt.AlignCenter)
        self.ploftedpass.setMaxLength(2)
        self.ploftedpass.setValidator(self.valid)
        self._STATS.append(self.ploftedpass)
        self.pheader = QtWidgets.QLineEdit(self.groupBox_3)
        self.pheader.setGeometry(QtCore.QRect(10, 250, 60, 25))
        self.pheader.setObjectName("pheader")
        self.pheader.setAlignment(QtCore.Qt.AlignCenter)
        self.pheader.setMaxLength(2)
        self.pheader.setValidator(self.valid)
        self._STATS.append(self.pheader)
        self.pswerve = QtWidgets.QLineEdit(self.groupBox_3)
        self.pswerve.setGeometry(QtCore.QRect(10, 280, 60, 25))
        self.pswerve.setObjectName("pswerve")
        self.pswerve.setAlignment(QtCore.Qt.AlignCenter)
        self.pswerve.setMaxLength(2)
        self.pswerve.setValidator(self.valid)
        self._STATS.append(self.pswerve)
        self.pcatching = QtWidgets.QLineEdit(self.groupBox_3)
        self.pcatching.setGeometry(QtCore.QRect(10, 310, 60, 25))
        self.pcatching.setObjectName("pcatching")
        self.pcatching.setAlignment(QtCore.Qt.AlignCenter)
        self.pcatching.setMaxLength(2)
        self.pcatching.setValidator(self.valid)
        self._STATS.append(self.pcatching)
        self.pclearing = QtWidgets.QLineEdit(self.groupBox_3)
        self.pclearing.setGeometry(QtCore.QRect(10, 340, 60, 25))
        self.pclearing.setObjectName("pclearing")
        self.pclearing.setAlignment(QtCore.Qt.AlignCenter)
        self.pclearing.setMaxLength(2)
        self.pclearing.setValidator(self.valid)
        self._STATS.append(self.pclearing)
        self.preflexes = QtWidgets.QLineEdit(self.groupBox_3)
        self.preflexes.setGeometry(QtCore.QRect(10, 370, 60, 25))
        self.preflexes.setObjectName("preflexes")
        self.preflexes.setAlignment(QtCore.Qt.AlignCenter)
        self.preflexes.setMaxLength(2)
        self.preflexes.setValidator(self.valid)
        self._STATS.append(self.preflexes)
        self.pstrball = QtWidgets.QLineEdit(self.groupBox_3)
        self.pstrball.setGeometry(QtCore.QRect(10, 400, 60, 25))
        self.pstrball.setObjectName("pstrball")
        self.pstrball.setAlignment(QtCore.Qt.AlignCenter)
        self.pstrball.setMaxLength(2)
        self.pstrball.setValidator(self.valid)
        self._STATS.append(self.pstrball)
        self.pphyscont = QtWidgets.QLineEdit(self.groupBox_3)
        self.pphyscont.setGeometry(QtCore.QRect(10, 430, 60, 25))
        self.pphyscont.setObjectName("pphyscont")
        self.pphyscont.setAlignment(QtCore.Qt.AlignCenter)
        self.pphyscont.setMaxLength(2)
        self.pphyscont.setValidator(self.valid)
        self._STATS.append(self.pphyscont)
        self.pkickpower = QtWidgets.QLineEdit(self.groupBox_3)
        self.pkickpower.setGeometry(QtCore.QRect(10, 460, 60, 25))
        self.pkickpower.setObjectName("pkickpower")
        self.pkickpower.setAlignment(QtCore.Qt.AlignCenter)
        self.pkickpower.setMaxLength(2)
        self.pkickpower.setValidator(self.valid)
        self._STATS.append(self.pkickpower)
        self.pexplopower = QtWidgets.QLineEdit(self.groupBox_3)
        self.pexplopower.setGeometry(QtCore.QRect(10, 490, 60, 25))
        self.pexplopower.setObjectName("pexplopower")
        self.pexplopower.setAlignment(QtCore.Qt.AlignCenter)
        self.pexplopower.setMaxLength(2)
        self.pexplopower.setValidator(self.valid)
        self._STATS.append(self.pexplopower)
        self.pballcontrol = QtWidgets.QLineEdit(self.groupBox_3)
        self.pballcontrol.setGeometry(QtCore.QRect(10, 520, 60, 25))
        self.pballcontrol.setObjectName("pballcontrol")
        self.pballcontrol.setAlignment(QtCore.Qt.AlignCenter)
        self.pballcontrol.setMaxLength(2)
        self.pballcontrol.setValidator(self.valid)
        self._STATS.append(self.pballcontrol)
        self.pballwinning = QtWidgets.QLineEdit(self.groupBox_3)
        self.pballwinning.setGeometry(QtCore.QRect(10, 550, 60, 25))
        self.pballwinning.setObjectName("pballwinning")
        self.pballwinning.setAlignment(QtCore.Qt.AlignCenter)
        self.pballwinning.setMaxLength(2)
        self.pballwinning.setValidator(self.valid)
        self._STATS.append(self.pballwinning)
        self.pjump = QtWidgets.QLineEdit(self.groupBox_3)
        self.pjump.setGeometry(QtCore.QRect(10, 580, 60, 25))
        self.pjump.setObjectName("pjump")
        self.pjump.setAlignment(QtCore.Qt.AlignCenter)
        self.pjump.setMaxLength(2)
        self.pjump.setValidator(self.valid)
        self._STATS.append(self.pjump)
        self.pcoverage = QtWidgets.QLineEdit(self.groupBox_3)
        self.pcoverage.setGeometry(QtCore.QRect(10, 610, 60, 25))
        self.pcoverage.setObjectName("pcoverage")
        self.pcoverage.setAlignment(QtCore.Qt.AlignCenter)
        self.pcoverage.setMaxLength(2)
        self.pcoverage.setValidator(self.valid)
        self._STATS.append(self.pcoverage)
        self.pplacekicking = QtWidgets.QLineEdit(self.groupBox_3)
        self.pplacekicking.setGeometry(QtCore.QRect(10, 640, 60, 25))
        self.pplacekicking.setObjectName("pplacekicking")
        self.pplacekicking.setAlignment(QtCore.Qt.AlignCenter)
        self.pplacekicking.setMaxLength(2)
        self.pplacekicking.setValidator(self.valid)
        self._STATS.append(self.pplacekicking)
        self.pstamina = QtWidgets.QLineEdit(self.groupBox_3)
        self.pstamina.setGeometry(QtCore.QRect(10, 670, 60, 25))
        self.pstamina.setObjectName("pstamina")
        self.pstamina.setAlignment(QtCore.Qt.AlignCenter)
        self.pstamina.setMaxLength(2)
        self.pstamina.setValidator(self.valid)
        self._STATS.append(self.pstamina)
        self.pspeed = QtWidgets.QLineEdit(self.groupBox_3)
        self.pspeed.setGeometry(QtCore.QRect(10, 700, 60, 25))
        self.pspeed.setObjectName("pspeed")
        self.pspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.pspeed.setMaxLength(2)
        self.pspeed.setValidator(self.valid)
        self._STATS.append(self.pspeed)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(90, 40, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(90, 70, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(90, 100, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(90, 130, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(90, 160, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(90, 190, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(90, 220, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(90, 250, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(90, 280, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(90, 310, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(90, 340, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(90, 370, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setGeometry(QtCore.QRect(90, 400, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(90, 430, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setGeometry(QtCore.QRect(90, 460, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(90, 490, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(90, 520, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_3)
        self.label_37.setGeometry(QtCore.QRect(90, 550, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setGeometry(QtCore.QRect(90, 580, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_3)
        self.label_39.setGeometry(QtCore.QRect(90, 610, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_3)
        self.label_40.setGeometry(QtCore.QRect(90, 640, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_3)
        self.label_41.setGeometry(QtCore.QRect(90, 670, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setGeometry(QtCore.QRect(90, 700, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(620, 700, 221, 121))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_43 = QtWidgets.QLabel(self.groupBox_4)
        self.label_43.setGeometry(QtCore.QRect(0, 0, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.padjust = QtWidgets.QLineEdit(self.groupBox_4)
        self.padjust.setGeometry(QtCore.QRect(10, 55, 61, 25))
        self.padjust.setObjectName("padjust")
        self.padjust.setMaxLength(3)
        self.padjust.setValidator(QtGui.QIntValidator(0, 999))
        self.padplus = QtWidgets.QPushButton(self.groupBox_4)
        self.padplus.setGeometry(QtCore.QRect(80, 40, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.padplus.setFont(font)
        self.padplus.setObjectName("padplus")
        self.padminus = QtWidgets.QPushButton(self.groupBox_4)
        self.padminus.setGeometry(QtCore.QRect(150, 40, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.padminus.setFont(font)
        self.padminus.setObjectName("padminus")
        self.padequ = QtWidgets.QPushButton(self.groupBox_4)
        self.padequ.setGeometry(QtCore.QRect(80, 70, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.padequ.setFont(font)
        self.padequ.setObjectName("padequ")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(620, 10, 221, 681))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_44 = QtWidgets.QLabel(self.groupBox_5)
        self.label_44.setGeometry(QtCore.QRect(0, 0, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.pscissors = QtWidgets.QCheckBox(self.groupBox_5)
        self.pscissors.setGeometry(QtCore.QRect(10, 40, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pscissors.setFont(font)
        self.pscissors.setObjectName("pscissors")
        self._SKILLS.append(self.pscissors)
        self.pflipflap = QtWidgets.QCheckBox(self.groupBox_5)
        self.pflipflap.setGeometry(QtCore.QRect(10, 60, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pflipflap.setFont(font)
        self.pflipflap.setObjectName("pflipflap")
        self._SKILLS.append(self.pflipflap)
        self.pmarseille = QtWidgets.QCheckBox(self.groupBox_5)
        self.pmarseille.setGeometry(QtCore.QRect(10, 80, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pmarseille.setFont(font)
        self.pmarseille.setObjectName("pmarseille")
        self._SKILLS.append(self.pmarseille)
        self.psombrero = QtWidgets.QCheckBox(self.groupBox_5)
        self.psombrero.setGeometry(QtCore.QRect(10, 100, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.psombrero.setFont(font)
        self.psombrero.setObjectName("psombrero")
        self._SKILLS.append(self.psombrero)
        self.pcutbehind = QtWidgets.QCheckBox(self.groupBox_5)
        self.pcutbehind.setGeometry(QtCore.QRect(10, 120, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pcutbehind.setFont(font)
        self.pcutbehind.setObjectName("pcutbehind")
        self._SKILLS.append(self.pcutbehind)
        self.pscotch = QtWidgets.QCheckBox(self.groupBox_5)
        self.pscotch.setGeometry(QtCore.QRect(10, 140, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pscotch.setFont(font)
        self.pscotch.setObjectName("pscotch")
        self._SKILLS.append(self.pscotch)
        self.pheading = QtWidgets.QCheckBox(self.groupBox_5)
        self.pheading.setGeometry(QtCore.QRect(10, 160, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pheading.setFont(font)
        self.pheading.setObjectName("pheading")
        self._SKILLS.append(self.pheading)
        self.plrd = QtWidgets.QCheckBox(self.groupBox_5)
        self.plrd.setGeometry(QtCore.QRect(10, 180, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plrd.setFont(font)
        self.plrd.setObjectName("plrd")
        self._SKILLS.append(self.plrd)
        self.pknuckle = QtWidgets.QCheckBox(self.groupBox_5)
        self.pknuckle.setGeometry(QtCore.QRect(10, 200, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pknuckle.setFont(font)
        self.pknuckle.setObjectName("pknuckle")
        self._SKILLS.append(self.pknuckle)
        self.pacrofinish = QtWidgets.QCheckBox(self.groupBox_5)
        self.pacrofinish.setGeometry(QtCore.QRect(10, 220, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pacrofinish.setFont(font)
        self.pacrofinish.setObjectName("pacrofinish")
        self._SKILLS.append(self.pacrofinish)
        self.pheeltrick = QtWidgets.QCheckBox(self.groupBox_5)
        self.pheeltrick.setGeometry(QtCore.QRect(10, 240, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pheeltrick.setFont(font)
        self.pheeltrick.setObjectName("pheeltrick")
        self._SKILLS.append(self.pheeltrick)
        self.pfts = QtWidgets.QCheckBox(self.groupBox_5)
        self.pfts.setGeometry(QtCore.QRect(10, 260, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pfts.setFont(font)
        self.pfts.setObjectName("pfts")
        self._SKILLS.append(self.pfts)
        self.potp = QtWidgets.QCheckBox(self.groupBox_5)
        self.potp.setGeometry(QtCore.QRect(10, 280, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.potp.setFont(font)
        self.potp.setObjectName("potp")
        self._SKILLS.append(self.potp)
        self.pweightedpass = QtWidgets.QCheckBox(self.groupBox_5)
        self.pweightedpass.setGeometry(QtCore.QRect(10, 300, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pweightedpass.setFont(font)
        self.pweightedpass.setObjectName("pweightedpass")
        self._SKILLS.append(self.pweightedpass)
        self.ppinpointcross = QtWidgets.QCheckBox(self.groupBox_5)
        self.ppinpointcross.setGeometry(QtCore.QRect(10, 320, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ppinpointcross.setFont(font)
        self.ppinpointcross.setObjectName("ppinpointcross")
        self._SKILLS.append(self.ppinpointcross)
        self.pcurler = QtWidgets.QCheckBox(self.groupBox_5)
        self.pcurler.setGeometry(QtCore.QRect(10, 340, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pcurler.setFont(font)
        self.pcurler.setObjectName("pcurler")
        self._SKILLS.append(self.pcurler)
        self.prabona = QtWidgets.QCheckBox(self.groupBox_5)
        self.prabona.setGeometry(QtCore.QRect(10, 360, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.prabona.setFont(font)
        self.prabona.setObjectName("prabona")
        self._SKILLS.append(self.prabona)
        self.plowloftpass = QtWidgets.QCheckBox(self.groupBox_5)
        self.plowloftpass.setGeometry(QtCore.QRect(10, 380, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plowloftpass.setFont(font)
        self.plowloftpass.setObjectName("plowloftpass")
        self._SKILLS.append(self.plowloftpass)
        self.plowpunt = QtWidgets.QCheckBox(self.groupBox_5)
        self.plowpunt.setGeometry(QtCore.QRect(10, 400, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plowpunt.setFont(font)
        self.plowpunt.setObjectName("plowpunt")
        self._SKILLS.append(self.plowpunt)
        self.plongthrow = QtWidgets.QCheckBox(self.groupBox_5)
        self.plongthrow.setGeometry(QtCore.QRect(10, 420, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plongthrow.setFont(font)
        self.plongthrow.setObjectName("plongthrow")
        self._SKILLS.append(self.plongthrow)
        self.pgklongthrow = QtWidgets.QCheckBox(self.groupBox_5)
        self.pgklongthrow.setGeometry(QtCore.QRect(10, 440, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pgklongthrow.setFont(font)
        self.pgklongthrow.setObjectName("pgklongthrow")
        self._SKILLS.append(self.pgklongthrow)
        self.pmalicia = QtWidgets.QCheckBox(self.groupBox_5)
        self.pmalicia.setGeometry(QtCore.QRect(10, 460, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pmalicia.setFont(font)
        self.pmalicia.setObjectName("pmalicia")
        self._SKILLS.append(self.pmalicia)
        self.pmanmark = QtWidgets.QCheckBox(self.groupBox_5)
        self.pmanmark.setGeometry(QtCore.QRect(10, 480, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pmanmark.setFont(font)
        self.pmanmark.setObjectName("pmanmark")
        self._SKILLS.append(self.pmanmark)
        self.ptrackback = QtWidgets.QCheckBox(self.groupBox_5)
        self.ptrackback.setGeometry(QtCore.QRect(10, 500, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ptrackback.setFont(font)
        self.ptrackback.setObjectName("ptrackback")
        self._SKILLS.append(self.ptrackback)
        self.pacroclear = QtWidgets.QCheckBox(self.groupBox_5)
        self.pacroclear.setGeometry(QtCore.QRect(10, 520, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pacroclear.setFont(font)
        self.pacroclear.setObjectName("pacroclear")
        self._SKILLS.append(self.pacroclear)
        self.pcaptaincy = QtWidgets.QCheckBox(self.groupBox_5)
        self.pcaptaincy.setGeometry(QtCore.QRect(10, 540, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pcaptaincy.setFont(font)
        self.pcaptaincy.setObjectName("pcaptaincy")
        self._SKILLS.append(self.pcaptaincy)
        self.psupersub = QtWidgets.QCheckBox(self.groupBox_5)
        self.psupersub.setGeometry(QtCore.QRect(10, 560, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.psupersub.setFont(font)
        self.psupersub.setObjectName("psupersub")
        self._SKILLS.append(self.psupersub)
        self.pfightspirit = QtWidgets.QCheckBox(self.groupBox_5)
        self.pfightspirit.setGeometry(QtCore.QRect(10, 580, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pfightspirit.setFont(font)
        self.pfightspirit.setObjectName("pfightspirit")
        self._SKILLS.append(self.pfightspirit)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(850, 530, 221, 161))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_45 = QtWidgets.QLabel(self.groupBox_6)
        self.label_45.setGeometry(QtCore.QRect(0, 0, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.makegold = QtWidgets.QPushButton(self.groupBox_6)
        self.makegold.setGeometry(QtCore.QRect(60, 40, 93, 28))
        self.makegold.setObjectName("makegold")
        self.makesilver = QtWidgets.QPushButton(self.groupBox_6)
        self.makesilver.setGeometry(QtCore.QRect(60, 80, 93, 28))
        self.makesilver.setObjectName("makesilver")
        self.makebronze = QtWidgets.QPushButton(self.groupBox_6)
        self.makebronze.setGeometry(QtCore.QRect(60, 120, 93, 28))
        self.makebronze.setObjectName("makebronze")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(850, 10, 221, 191))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_46 = QtWidgets.QLabel(self.groupBox_7)
        self.label_46.setGeometry(QtCore.QRect(0, 0, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.ptrickster = QtWidgets.QCheckBox(self.groupBox_7)
        self.ptrickster.setGeometry(QtCore.QRect(10, 40, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ptrickster.setFont(font)
        self.ptrickster.setObjectName("ptrickster")
        self._COMSTYLES.append(self.ptrickster)
        self.pmazingrun = QtWidgets.QCheckBox(self.groupBox_7)
        self.pmazingrun.setGeometry(QtCore.QRect(10, 60, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pmazingrun.setFont(font)
        self.pmazingrun.setObjectName("pmazingrun")
        self._COMSTYLES.append(self.pmazingrun)
        self.pspeedbullet = QtWidgets.QCheckBox(self.groupBox_7)
        self.pspeedbullet.setGeometry(QtCore.QRect(10, 80, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pspeedbullet.setFont(font)
        self.pspeedbullet.setObjectName("pspeedbullet")
        self._COMSTYLES.append(self.pspeedbullet)
        self.pincisiverun = QtWidgets.QCheckBox(self.groupBox_7)
        self.pincisiverun.setGeometry(QtCore.QRect(10, 100, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pincisiverun.setFont(font)
        self.pincisiverun.setObjectName("pincisiverun")
        self._COMSTYLES.append(self.pincisiverun)
        self.plongball = QtWidgets.QCheckBox(self.groupBox_7)
        self.plongball.setGeometry(QtCore.QRect(10, 120, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plongball.setFont(font)
        self.plongball.setObjectName("plongball")
        self._COMSTYLES.append(self.plongball)
        self.pearlycross = QtWidgets.QCheckBox(self.groupBox_7)
        self.pearlycross.setGeometry(QtCore.QRect(10, 140, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pearlycross.setFont(font)
        self.pearlycross.setObjectName("pearlycross")
        self._COMSTYLES.append(self.pearlycross)
        self.plongranger = QtWidgets.QCheckBox(self.groupBox_7)
        self.plongranger.setGeometry(QtCore.QRect(10, 160, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plongranger.setFont(font)
        self.plongranger.setObjectName("plongranger")
        self._COMSTYLES.append(self.plongranger)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(850, 210, 221, 311))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_47 = QtWidgets.QLabel(self.groupBox_8)
        self.label_47.setGeometry(QtCore.QRect(0, 0, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.pdribhunch = QtWidgets.QComboBox(self.groupBox_8)
        self.pdribhunch.setGeometry(QtCore.QRect(140, 40, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pdribhunch.setFont(font)
        self.pdribhunch.setObjectName("pdribhunch")
        
        for i in range(3):
            self.pdribhunch.addItem(str(i+1), i)
        
        self.pdribarm = QtWidgets.QComboBox(self.groupBox_8)
        self.pdribarm.setGeometry(QtCore.QRect(140, 70, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pdribarm.setFont(font)
        self.pdribarm.setObjectName("pdribarm")
        self.pdribarm.setMaxVisibleItems(20)
        
        for i in range(8):
            self.pdribarm.addItem(str(i+1), i)
        
        self.prunhunch = QtWidgets.QComboBox(self.groupBox_8)
        self.prunhunch.setGeometry(QtCore.QRect(140, 100, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.prunhunch.setFont(font)
        self.prunhunch.setObjectName("prunhunch")
        self.prunhunch.setMaxVisibleItems(20)
        
        for i in range(3):
            self.prunhunch.addItem(str(i+1), i)
        
        self.prunarm = QtWidgets.QComboBox(self.groupBox_8)
        self.prunarm.setGeometry(QtCore.QRect(140, 130, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.prunarm.setFont(font)
        self.prunarm.setObjectName("prunarm")
        self.prunarm.setMaxVisibleItems(20)
        
        for i in range(8):
            self.prunarm.addItem(str(i+1), i)
        
        self.pckmot = QtWidgets.QComboBox(self.groupBox_8)
        self.pckmot.setGeometry(QtCore.QRect(140, 160, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pckmot.setFont(font)
        self.pckmot.setObjectName("pckmot")
        self.pckmot.setMaxVisibleItems(20)
        
        for i in range(6):
            self.pckmot.addItem(str(i+1), i)
        
        self.pfkmot = QtWidgets.QComboBox(self.groupBox_8)
        self.pfkmot.setGeometry(QtCore.QRect(140, 190, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pfkmot.setFont(font)
        self.pfkmot.setObjectName("pfkmot")
        self.pfkmot.setMaxVisibleItems(20)
        
        for i in range(16):
            self.pfkmot.addItem(str(i+1), i)
        
        self.ppkmot = QtWidgets.QComboBox(self.groupBox_8)
        self.ppkmot.setGeometry(QtCore.QRect(140, 220, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ppkmot.setFont(font)
        self.ppkmot.setObjectName("ppkmot")
        self.ppkmot.setMaxVisibleItems(20)
        
        for i in range(4):
            self.ppkmot.addItem(str(i+1), i)

        self.pgoalcel1 = QtWidgets.QComboBox(self.groupBox_8)
        self.pgoalcel1.setGeometry(QtCore.QRect(140, 250, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pgoalcel1.setFont(font)
        self.pgoalcel1.setObjectName("pgoalcel1")
        self.pgoalcel1.setMaxVisibleItems(20)
        
        self.pgoalcel1.addItem("None", 0)
        for i in range(127):
            self.pgoalcel1.addItem(str(i+1), i+1)
        
        self.pgoalcel2 = QtWidgets.QComboBox(self.groupBox_8)
        self.pgoalcel2.setGeometry(QtCore.QRect(140, 280, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pgoalcel2.setFont(font)
        self.pgoalcel2.setObjectName("pgoalcel2")
        self.pgoalcel2.setMaxVisibleItems(20)
        
        self.pgoalcel2.addItem("None", 0)
        for i in range(122):
            self.pgoalcel2.addItem(str(i+1), i+1)
        
        self.label_48 = QtWidgets.QLabel(self.groupBox_8)
        self.label_48.setGeometry(QtCore.QRect(10, 40, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_8)
        self.label_49.setGeometry(QtCore.QRect(10, 70, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_8)
        self.label_50.setGeometry(QtCore.QRect(10, 100, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_8)
        self.label_51.setGeometry(QtCore.QRect(10, 130, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_8)
        self.label_52.setGeometry(QtCore.QRect(10, 160, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_8)
        self.label_53.setGeometry(QtCore.QRect(10, 190, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_8)
        self.label_54.setGeometry(QtCore.QRect(10, 220, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.groupBox_8)
        self.label_55.setGeometry(QtCore.QRect(10, 250, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_8)
        self.label_56.setGeometry(QtCore.QRect(10, 280, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 260, 671))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_57 = QtWidgets.QLabel(self.groupBox_9)
        self.label_57.setGeometry(QtCore.QRect(0, 0, 260, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.pfacee = QtWidgets.QCheckBox(self.groupBox_9)
        self.pfacee.setGeometry(QtCore.QRect(10, 40, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pfacee.setFont(font)
        self.pfacee.setObjectName("pfacee")
        self.phaire = QtWidgets.QCheckBox(self.groupBox_9)
        self.phaire.setGeometry(QtCore.QRect(10, 60, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.phaire.setFont(font)
        self.phaire.setObjectName("phaire")
        self.pphyse = QtWidgets.QCheckBox(self.groupBox_9)
        self.pphyse.setGeometry(QtCore.QRect(10, 80, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pphyse.setFont(font)
        self.pphyse.setObjectName("pphyse")
        self.pstripe = QtWidgets.QCheckBox(self.groupBox_9)
        self.pstripe.setGeometry(QtCore.QRect(10, 100, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pstripe.setFont(font)
        self.pstripe.setObjectName("pstripe")
        self.pskincol = QtWidgets.QComboBox(self.groupBox_9)
        self.pskincol.setGeometry(QtCore.QRect(102, 130, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pskincol.setFont(font)
        self.pskincol.setObjectName("pskincol")
        
        for id, col in self._SKINCOLOURS.items():
            self.pskincol.addItem(col, id)
        
        self.label_58 = QtWidgets.QLabel(self.groupBox_9)
        self.label_58.setGeometry(QtCore.QRect(10, 130, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.groupBox_9)
        self.label_59.setGeometry(QtCore.QRect(10, 160, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_9)
        self.label_60.setGeometry(QtCore.QRect(10, 190, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.pgkgloves = QtWidgets.QLineEdit(self.groupBox_9)
        self.pgkgloves.setGeometry(QtCore.QRect(100, 160, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pgkgloves.setFont(font)
        self.pgkgloves.setObjectName("pgkgloves")
        self.pgkgloves.setMaxLength(3)
        self.pgkgloves.setValidator(QtGui.QIntValidator(0, 999))
        self.pboots = QtWidgets.QLineEdit(self.groupBox_9)
        self.pboots.setGeometry(QtCore.QRect(100, 190, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pboots.setFont(font)
        self.pboots.setObjectName("pboots")
        self.pboots.setMaxLength(4)
        self.pboots.setValidator(QtGui.QIntValidator(0, 9999))
        
        self.label_61 = QtWidgets.QLabel(self.groupBox_9)
        self.label_61.setGeometry(QtCore.QRect(10, 220, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.groupBox_9)
        self.label_62.setGeometry(QtCore.QRect(10, 250, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_9)
        self.label_63.setGeometry(QtCore.QRect(10, 310, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_9)
        self.label_64.setGeometry(QtCore.QRect(10, 280, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.pwristtape = QtWidgets.QComboBox(self.groupBox_9)
        self.pwristtape.setGeometry(QtCore.QRect(100, 220, 150, 25))
        self.pwristtape.setObjectName("pwristtape")
        
        self.pwristtape.addItem("Off (No Replacements)", 0)
        self.pwristtape.addItem("Right (Tight Tucked)", 1)
        self.pwristtape.addItem("Left (Collar+Pants)", 2)
        self.pwristtape.addItem("Both (C+P and TT)", 3)
        
        self.psleeves = QtWidgets.QComboBox(self.groupBox_9)
        self.psleeves.setGeometry(QtCore.QRect(100, 250, 150, 25))
        self.psleeves.setObjectName("psleeves")
        
        self.psleeves.addItem("Hybrid", 0)
        self.psleeves.addItem("Short", 1)
        self.psleeves.addItem("Long", 2)
        
        self.pshirttail = QtWidgets.QComboBox(self.groupBox_9)
        self.pshirttail.setGeometry(QtCore.QRect(100, 280, 150, 25))
        self.pshirttail.setObjectName("pshirttail")
        
        self.pshirttail.addItem("Tucked", 0)
        self.pshirttail.addItem("Untucked", 1)
        
        self.psocks = QtWidgets.QComboBox(self.groupBox_9)
        self.psocks.setGeometry(QtCore.QRect(100, 310, 150, 25))
        self.psocks.setObjectName("psocks")
        
        self.psocks.addItem("Standard", 0)
        self.psocks.addItem("Long", 1)
        self.psocks.addItem("Short", 2)
        
        self.pankletape = QtWidgets.QCheckBox(self.groupBox_9)
        self.pankletape.setGeometry(QtCore.QRect(10, 400, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pankletape.setFont(font)
        self.pankletape.setObjectName("pankletape")
        self.label_65 = QtWidgets.QLabel(self.groupBox_9)
        self.label_65.setGeometry(QtCore.QRect(10, 340, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.pglasses = QtWidgets.QComboBox(self.groupBox_9)
        self.pglasses.setGeometry(QtCore.QRect(100, 340, 150, 25))
        self.pglasses.setObjectName("pglasses")
        self.pglasses.addItem("No Glasses", 0)
        for i in range(7):
            self.pglasses.addItem("Type " + str(i+1), i+1)
        
        self.pshorts = QtWidgets.QComboBox(self.groupBox_9)
        self.pshorts.setGeometry(QtCore.QRect(100, 370, 150, 25))
        self.pshorts.setObjectName("pshorts")
        
        self.pshorts.addItem("Off/Off", 0)
        self.pshorts.addItem("Short/Short", 1)
        self.pshorts.addItem("Off/Long", 2)
        self.pshorts.addItem("Short/Long", 3)
        
        self.label_66 = QtWidgets.QLabel(self.groupBox_9)
        self.label_66.setGeometry(QtCore.QRect(10, 370, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        
        
        
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setGeometry(QtCore.QRect(850, 700, 221, 120))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.paccept = QtWidgets.QPushButton(self.groupBox_10)
        self.paccept.setGeometry(QtCore.QRect(30, 10, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.paccept.setFont(font)
        self.paccept.setObjectName("paccept")
        self.pcancel = QtWidgets.QPushButton(self.groupBox_10)
        self.pcancel.setGeometry(QtCore.QRect(30, 60, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pcancel.setFont(font)
        self.pcancel.setObjectName("pcancel")
        
        
        self.pfpc = QtWidgets.QPushButton(self.groupBox_9)
        self.pfpc.setGeometry(QtCore.QRect(65, 460, 120, 35))
        self.pfpc.setObjectName("pfpc")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(280, 10, 220, 551))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_67 = QtWidgets.QLabel(self.groupBox_11)
        self.label_67.setGeometry(QtCore.QRect(0, 0, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_11)
        self.label_68.setGeometry(QtCore.QRect(10, 40, 101, 25))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_11)
        self.label_69.setGeometry(QtCore.QRect(10, 70, 101, 25))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_11)
        self.label_70.setGeometry(QtCore.QRect(10, 100, 101, 25))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.groupBox_11)
        self.label_71.setGeometry(QtCore.QRect(10, 130, 101, 25))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupBox_11)
        self.label_72.setGeometry(QtCore.QRect(10, 160, 121, 25))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.groupBox_11)
        self.label_73.setGeometry(QtCore.QRect(10, 220, 101, 25))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.groupBox_11)
        self.label_74.setGeometry(QtCore.QRect(10, 190, 101, 25))
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.groupBox_11)
        self.label_75.setGeometry(QtCore.QRect(10, 250, 101, 25))
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.groupBox_11)
        self.label_76.setGeometry(QtCore.QRect(10, 310, 101, 25))
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.groupBox_11)
        self.label_77.setGeometry(QtCore.QRect(10, 340, 101, 25))
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.groupBox_11)
        self.label_78.setGeometry(QtCore.QRect(10, 280, 101, 25))
        self.label_78.setObjectName("label_78")
        self.pneckl = QtWidgets.QSpinBox(self.groupBox_11)
        self.pneckl.setGeometry(QtCore.QRect(140, 160, 71, 25))
        self.pneckl.setObjectName("pneckl")
        self.pneckl.setRange(-7, 7)
        self.pnecks = QtWidgets.QSpinBox(self.groupBox_11)
        self.pnecks.setGeometry(QtCore.QRect(140, 40, 71, 25))
        self.pnecks.setObjectName("pnecks")
        self.pnecks.setRange(-7, 7)
        self.pshoulderh = QtWidgets.QSpinBox(self.groupBox_11)
        self.pshoulderh.setGeometry(QtCore.QRect(140, 70, 71, 25))
        self.pshoulderh.setObjectName("pshoulderh")
        self.pshoulderh.setRange(-7, 7)
        self.pshoulderw = QtWidgets.QSpinBox(self.groupBox_11)
        self.pshoulderw.setGeometry(QtCore.QRect(140, 100, 71, 25))
        self.pshoulderw.setObjectName("pshoulderw")
        self.pshoulderw.setRange(-7, 7)
        self.pchestm = QtWidgets.QSpinBox(self.groupBox_11)
        self.pchestm.setGeometry(QtCore.QRect(140, 130, 71, 25))
        self.pchestm.setObjectName("pchestm")
        self.pchestm.setRange(-7, 7)
        self.pwaists = QtWidgets.QSpinBox(self.groupBox_11)
        self.pwaists.setGeometry(QtCore.QRect(140, 190, 71, 25))
        self.pwaists.setObjectName("pwaists")
        self.pwaists.setRange(-7, 7)
        self.parms = QtWidgets.QSpinBox(self.groupBox_11)
        self.parms.setGeometry(QtCore.QRect(140, 280, 71, 25))
        self.parms.setObjectName("parms")
        self.parms.setRange(-7, 7)
        self.pthighs = QtWidgets.QSpinBox(self.groupBox_11)
        self.pthighs.setGeometry(QtCore.QRect(140, 220, 71, 25))
        self.pthighs.setObjectName("pthighs")
        self.pthighs.setRange(-7, 7)
        self.pcalfs = QtWidgets.QSpinBox(self.groupBox_11)
        self.pcalfs.setGeometry(QtCore.QRect(140, 250, 71, 25))
        self.pcalfs.setObjectName("pcalfs")
        self.pcalfs.setRange(-7, 7)
        self.plegl = QtWidgets.QSpinBox(self.groupBox_11)
        self.plegl.setGeometry(QtCore.QRect(140, 310, 71, 25))
        self.plegl.setObjectName("plegl")
        self.plegl.setRange(-7, 7)
        self.parml = QtWidgets.QSpinBox(self.groupBox_11)
        self.parml.setGeometry(QtCore.QRect(140, 340, 71, 25))
        self.parml.setObjectName("parml")
        self.parml.setRange(-7, 7)
        self.label_79 = QtWidgets.QLabel(self.groupBox_11)
        self.label_79.setGeometry(QtCore.QRect(10, 400, 101, 25))
        self.label_79.setObjectName("label_79")
        self.pheadl = QtWidgets.QSpinBox(self.groupBox_11)
        self.pheadl.setGeometry(QtCore.QRect(140, 370, 71, 25))
        self.pheadl.setObjectName("pheadl")
        self.pheadl.setRange(-7, 7)
        self.label_80 = QtWidgets.QLabel(self.groupBox_11)
        self.label_80.setGeometry(QtCore.QRect(10, 430, 101, 25))
        self.label_80.setObjectName("label_80")
        self.pheadw = QtWidgets.QSpinBox(self.groupBox_11)
        self.pheadw.setGeometry(QtCore.QRect(140, 400, 71, 25))
        self.pheadw.setObjectName("pheadw")
        self.pheadw.setRange(-7, 7)
        self.label_81 = QtWidgets.QLabel(self.groupBox_11)
        self.label_81.setGeometry(QtCore.QRect(10, 370, 101, 25))
        self.label_81.setObjectName("label_81")
        self.pheadd = QtWidgets.QSpinBox(self.groupBox_11)
        self.pheadd.setGeometry(QtCore.QRect(140, 430, 71, 25))
        self.pheadd.setObjectName("pheadd")
        self.pheadd.setRange(-7, 7)
        self.label_82 = QtWidgets.QLabel(self.groupBox_11)
        self.label_82.setGeometry(QtCore.QRect(0, 460, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_82.setFont(font)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.ppset = QtWidgets.QPushButton(self.groupBox_11)
        self.ppset.setGeometry(QtCore.QRect(90, 500, 120, 35))
        self.ppset.setObjectName("ppset")
        self.ppsete = QtWidgets.QLineEdit(self.groupBox_11)
        self.ppsete.setGeometry(QtCore.QRect(10, 505, 71, 25))
        self.ppsete.setObjectName("ppsete")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setGeometry(QtCore.QRect(280, 570, 221, 110))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.paaccept = QtWidgets.QPushButton(self.groupBox_12)
        self.paaccept.setGeometry(QtCore.QRect(30, 10, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.paaccept.setFont(font)
        self.paaccept.setObjectName("paaccept")
        self.pacancel = QtWidgets.QPushButton(self.groupBox_12)
        self.pacancel.setGeometry(QtCore.QRect(30, 60, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pacancel.setFont(font)
        self.pacancel.setObjectName("pacancel")
        
        self.tabWidget.addTab(self.tab_2, "")
        Player.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Player)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        Player.setMenuBar(self.menubar)

        self.retranslateUi(Player)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Player)

    def retranslateUi(self, Player):
        _translate = QtCore.QCoreApplication.translate
        Player.setWindowTitle(_translate("Player", "Player Editor"))
        self.label.setText(_translate("Player", "General"))
        self.label_2.setText(_translate("Player", "Player ID:"))
        self.label_3.setText(_translate("Player", "Name:"))
        self.label_4.setText(_translate("Player", "Shirt Name:"))
        self.label_5.setText(_translate("Player", "Commentary:"))
        self.label_6.setText(_translate("Player", "Nationality:"))
        self.label_7.setText(_translate("Player", "Playing Style:"))
        self.label_8.setText(_translate("Player", "Age:"))
        self.label_9.setText(_translate("Player", "Height cm:"))
        self.label_10.setText(_translate("Player", "Weight kg:"))
        self.label_12.setText(_translate("Player", "Form:"))
        self.label_13.setText(_translate("Player", "Stronger Foot:"))
        self.label_14.setText(_translate("Player", "WF Acc/Usage:"))
        self.label_15.setText(_translate("Player", "Injury Res:"))
        self.label_16.setText(_translate("Player", "Position"))
        self.label_17.setText(_translate("Player", "Registered Pos:"))
        self.label_18.setText(_translate("Player", "Playable Pos:"))
        self.posss.setText(_translate("Player", "SS"))
        self.poscf.setText(_translate("Player", "CF"))
        self.poslwf.setText(_translate("Player", "LWF"))
        self.posamf.setText(_translate("Player", "AMF"))
        self.posrwf.setText(_translate("Player", "RWF"))
        self.poslmf.setText(_translate("Player", "LMF"))
        self.posdmf.setText(_translate("Player", "DMF"))
        self.poscmf.setText(_translate("Player", "CMF"))
        self.posrmf.setText(_translate("Player", "RMF"))
        self.poslb.setText(_translate("Player", "LB"))
        self.poscb.setText(_translate("Player", "CB"))
        self.posrb.setText(_translate("Player", "RB"))
        self.posgk.setText(_translate("Player", "GK"))
        self.label_19.setText(_translate("Player", "Abilities (1-99)"))
        self.label_20.setText(_translate("Player", "Attacking Prowess"))
        self.label_21.setText(_translate("Player", "Defensive Prowess"))
        self.label_22.setText(_translate("Player", "Goalkeeping"))
        self.label_23.setText(_translate("Player", "Dribbling"))
        self.label_24.setText(_translate("Player", "Finishing"))
        self.label_25.setText(_translate("Player", "Low Pass"))
        self.label_26.setText(_translate("Player", "Lofted Pass"))
        self.label_27.setText(_translate("Player", "Header"))
        self.label_28.setText(_translate("Player", "Swerve"))
        self.label_29.setText(_translate("Player", "Catching"))
        self.label_30.setText(_translate("Player", "Clearing"))
        self.label_31.setText(_translate("Player", "Reflexes"))
        self.label_32.setText(_translate("Player", "Body Control"))
        self.label_33.setText(_translate("Player", "Physical Contact"))
        self.label_34.setText(_translate("Player", "Kicking Power"))
        self.label_35.setText(_translate("Player", "Explosive Power"))
        self.label_36.setText(_translate("Player", "Ball Control"))
        self.label_37.setText(_translate("Player", "Ball Winning"))
        self.label_38.setText(_translate("Player", "Jump"))
        self.label_39.setText(_translate("Player", "Coverage"))
        self.label_40.setText(_translate("Player", "Place Kicking"))
        self.label_41.setText(_translate("Player", "Stamina"))
        self.label_42.setText(_translate("Player", "Speed"))
        self.label_43.setText(_translate("Player", "Adjust Abilities"))
        self.padplus.setText(_translate("Player", "+"))
        self.padminus.setText(_translate("Player", "-"))
        self.padequ.setText(_translate("Player", "="))
        self.label_44.setText(_translate("Player", "Player Skills (0/10)"))
        self.pscissors.setText(_translate("Player", "S01 - Scissors Feint"))
        self.pflipflap.setText(_translate("Player", "S02 - Flip Flap"))
        self.pmarseille.setText(_translate("Player", "S03 - Marseille Turn"))
        self.psombrero.setText(_translate("Player", "S04 - Sombrero"))
        self.pcutbehind.setText(_translate("Player", "S05 - Cut Behind/Turn"))
        self.pscotch.setText(_translate("Player", "S06 - Scotch Move"))
        self.pheading.setText(_translate("Player", "S07 - Heading"))
        self.plrd.setText(_translate("Player", "S08 - Long Range Drive"))
        self.pknuckle.setText(_translate("Player", "S09 - Knuckle Shot"))
        self.pacrofinish.setText(_translate("Player", "S10 - Acrobatic Finishing"))
        self.pheeltrick.setText(_translate("Player", "S11 - Heel Trick"))
        self.pfts.setText(_translate("Player", "S12 - First-time Shot"))
        self.potp.setText(_translate("Player", "S13 - One-touch Pass"))
        self.pweightedpass.setText(_translate("Player", "S14 - Weighted Pass"))
        self.ppinpointcross.setText(_translate("Player", "S15 - Pinpoint Crossing"))
        self.pcurler.setText(_translate("Player", "S16 - Outside Curler"))
        self.prabona.setText(_translate("Player", "S17 - Rabona"))
        self.plowloftpass.setText(_translate("Player", "S18 - Low Lofted Pass"))
        self.plowpunt.setText(_translate("Player", "S19 - Low Punt Trajectory"))
        self.plongthrow.setText(_translate("Player", "S20 - Long Throw"))
        self.pgklongthrow.setText(_translate("Player", "S21 - GK Long Throw"))
        self.pmalicia.setText(_translate("Player", "S22 - Malicia"))
        self.pmanmark.setText(_translate("Player", "S23 - Man Marking"))
        self.ptrackback.setText(_translate("Player", "S24 - Track Back"))
        self.pacroclear.setText(_translate("Player", "S25 - Acrobatic Clear"))
        self.pcaptaincy.setText(_translate("Player", "S26 - Captaincy"))
        self.psupersub.setText(_translate("Player", "S27 - Super Sub"))
        self.pfightspirit.setText(_translate("Player", "S28 - Fighting Spirit"))
        self.label_45.setText(_translate("Player", "4CC"))
        self.makegold.setText(_translate("Player", "Make Gold"))
        self.makesilver.setText(_translate("Player", "Make Silver"))
        self.makebronze.setText(_translate("Player", "Make Bronze"))
        self.label_46.setText(_translate("Player", "COM Styles (0/5)"))
        self.ptrickster.setText(_translate("Player", "P01 - Trickster"))
        self.pmazingrun.setText(_translate("Player", "P02 - Mazing Run"))
        self.pspeedbullet.setText(_translate("Player", "P03 - Speeding Bullet"))
        self.pincisiverun.setText(_translate("Player", "P04 - Incisive Run"))
        self.plongball.setText(_translate("Player", "P05 - Long Ball Expert"))
        self.pearlycross.setText(_translate("Player", "P06 - Early Cross"))
        self.plongranger.setText(_translate("Player", "P07 - Long ranger"))
        self.label_47.setText(_translate("Player", "Motions"))
        self.label_48.setText(_translate("Player", "Drib Hunch:"))
        self.label_49.setText(_translate("Player", "Drib Arm Move:"))
        self.label_50.setText(_translate("Player", "Run Hunch:"))
        self.label_51.setText(_translate("Player", "Run Arm Move:"))
        self.label_52.setText(_translate("Player", "CK Motion:"))
        self.label_53.setText(_translate("Player", "FK Motion:"))
        self.label_54.setText(_translate("Player", "PK Motion:"))
        self.label_55.setText(_translate("Player", "Goal Celeb 1:"))
        self.label_56.setText(_translate("Player", "Goal Celeb 2:"))
        self.label_57.setText(_translate("Player", "Player Appearance"))
        self.pfacee.setText(_translate("Player", "Edited Face Settings"))
        self.phaire.setText(_translate("Player", "Edited Hair Settings"))
        self.pphyse.setText(_translate("Player", "Edited Physique"))
        self.pstripe.setText(_translate("Player", "Edited Strip Style"))
        self.label_58.setText(_translate("Player", "Skin Colour:"))
        self.label_59.setText(_translate("Player", "GK Gloves:"))
        self.label_60.setText(_translate("Player", "Boots:"))
        self.paccept.setText(_translate("Player", "Accept"))
        self.pcancel.setText(_translate("Player", "Cancel"))
        self.label_61.setText(_translate("Player", "Wrist Tape:"))
        self.label_62.setText(_translate("Player", "Sleeves:"))
        self.label_63.setText(_translate("Player", "Socks:"))
        self.label_64.setText(_translate("Player", "Shirttail:"))
        self.pankletape.setText(_translate("Player", "Ankle Tape"))
        self.label_65.setText(_translate("Player", "Glasses:"))
        self.label_66.setText(_translate("Player", "Undershorts:"))
        self.pfpc.setText(_translate("Player", "Set FPC"))
        self.label_67.setText(_translate("Player", "Player Physique"))
        self.label_68.setText(_translate("Player", "Neck Length:"))
        self.label_69.setText(_translate("Player", "Neck Size:"))
        self.label_70.setText(_translate("Player", "Shoulder Height:"))
        self.label_71.setText(_translate("Player", "Shoulder Width:"))
        self.label_72.setText(_translate("Player", "Chest Measurement:"))
        self.label_73.setText(_translate("Player", "Arm Size:"))
        self.label_74.setText(_translate("Player", "Waist Size:"))
        self.label_75.setText(_translate("Player", "Thight Size:"))
        self.label_76.setText(_translate("Player", "Leg Length:"))
        self.label_77.setText(_translate("Player", "Arm Length:"))
        self.label_78.setText(_translate("Player", "Calf Size:"))
        self.label_79.setText(_translate("Player", "Head Width:"))
        self.label_80.setText(_translate("Player", "Head Depth:"))
        self.label_81.setText(_translate("Player", "Head Length:"))
        self.label_82.setText(_translate("Player", "Bulk Adjust"))
        self.ppset.setText(_translate("Player", "Set"))
        self.paaccept.setText(_translate("Player", "Accept"))
        self.pacancel.setText(_translate("Player", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Player", "Stats"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Player", "Appearance"))

